# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9bac4545a15ac34a064fa5aa7e72f150c5c184f9efabc32a238d9785d94bbf77cbe7f876fa44e7bf44f502c546114e1f6ec547f7d2a5f7945baa0581ebdcb90

test:
  secret_key_base: c1422b14726c38dd7517a96c5eb869875637a3267f841991ca3185a1633b78607674bb8cee1c939e0767d86bf803999da52d45fd595fcacddb5d091d6cbd0803

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
